[colors]
[colors.primary]
    background = '0x0f070d'
    foreground = '0xe5d3a2'

[colors.cursor]
    text   = '0xe5d3a2'
    cursor = '0x978771'

[colors.normal]
    black   = '0x0f070d'
    red     = '0xbe0e17'
    green   = '0x868715'
    yellow  = '0xcc871a'
    blue    = '0x377274'
    magenta = '0x9f4b73'
    cyan    = '0x568d57'
    white   = '0x978771'

[colors.bright]
    black   = '0x7f7060'
    red     = '0xf63028'
    green   = '0xa9b01d'
    yellow  = '0xf7b024'
    blue    = '0x709585'
    magenta = '0xc76f89'
    cyan    = '0x7db568'
    white   = '0xe5d3a2'

[font.normal]
  family = "FiraCode Nerd Font"
  style  = "Regular"
