require('after.lsp')
require('after.cmp')
require('after.alpha')
require('after.cmaketools')
require('after.powershell')
require('after.renamer')
require('after.statusline')
require('after.toggleterm')
require('after.treesitter')
require('after.webdevicons')
require('after.bettercomments')
require('after.whichkey')
-- Unfortunate, but necessary for GDB
vim.cmd('source ~/AppData/Local/nvim/lua/after/dispatch.vim')
